### ISSUE TITLE
Replacing Scripts/ckeditor to use custom build of CKEditor will fail... except...

### ISSUE THREAD

**Issue by jarollz** [inteno/CustomCK#1]
At first, I have a need to add color dialog button in my own ckeditor in OrchardCMS. However, after replacing the whole ckeditor folder from custom ckeditor build that was made by following the link inside CustomCK wiki, I saw that ckeditor decorations isn't shown when I attempt to create new page.

However by changing this last line from CustomCK orchard cms setting:

_from_

```
extraPlugins: 'medialibrary'
```

_to_

```
extraPlugins: 'customckentities,customckhtml,medialibrary'
```

then CustomCK finally become more powerful.

It seems CustomCKEntities and CustomCKHTML isn't optional when replacing ckeditor folder completely from custom build.

**Comment by matthiasjost** [comment]
Thank you for your feedback.

customckentities and customckhtml are plugins we wrote that reside in the plugin directory of CKEditor. You may remove them or take them as a reference how to write plugins for ckeditor.

The plugins are not referenced in other CKEditor sources.
The only way CKEditor notices the existence of these plugins is the extraPlugins parameter.
What can easily happen is that you have one character wrong in the configuration so that the whole CKEditor does not load properly. You may open the Chrome Developer tools before switching to the new content page.

If you are still sure about the behaviour you describe please post a new message and we will look into it.
